
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlwawblbszfuzczhdote.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsd2F3Ymxic3pmdXpjemhkb3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTkyNjksImV4cCI6MjA1OTU5NTI2OX0.Qi_IxQBth1YEG2q3lGCSLZ-OeKhSLHa6StrKiAP4RsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
